version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  mqtt-publisher:
    build:
      context: ./mqtt-publisher
    container_name: mqtt-publisher
    depends_on:
      - mosquitto

  mqtt-subscriber:
    build:
      context: ./mqtt-subscriber
    container_name: mqtt-subscriber
    depends_on:
      - mosquitto
      - mongodb

  fastapi-app:
    build:
      context: ./fastapi-app
    container_name: fastapi-app
    depends_on:
      - mqtt-subscriber
      - redis
    ports:
      - "80:80"

